'use client';

import './globals.css';

import GlobalStyle from './_styles/Global';
import { Inter } from 'next/font/google';
// import type { Metadata } from 'next';
import React from 'react';
import { ThemeProvider } from '@emotion/react';
import theme from './_styles/theme';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
